/// <summary>
/// Holds x,y,roomId is used by spawner, generated by translator.
/// Is Used by RoomFactory to spawn room prefabs with correct coordinates and rotation.
/// </summary>
public class RoomSpawnParameters
{
    public RoomSpawnParameters(float X, float Y, ushort roomId, bool isHorizontal = true)
    {
        this.X = X;
        this.Y = Y;
        RoomId = roomId;
        IsHorizontal = isHorizontal;
    }
    
    public float X { get; set; }
    public float Y { get; set; }
    public bool IsHorizontal;
    public ushort RoomId { get; set; }

}