/// <summary>
/// Holds x,y,roomId is used by spawner, generated by translator.
/// Is Used by RoomFactory to spawn room prefabs with correct coordinates and rotation.
/// </summary>
public class RoomSpawnParameters
{
    public RoomSpawnParameters(int id, float X, float Y, ushort roomId, bool isHorizontal = false)
    {
        this.ID = id;
        this.X = X;
        this.Y = Y;
        RoomId = roomId;
        IsHorizontal = isHorizontal;
    }

    public RoomSpawnParameters(float X, float Y, ushort roomId, bool isHorizontal = false)
    {
        this.X = X;
        this.Y = Y;
        RoomId = roomId;
        IsHorizontal = isHorizontal;
    }

    public int ID { get; set; }
    public float X { get; set; }
    public float Y { get; set; }
    public bool IsHorizontal = false;
    public ushort RoomId { get; set; }

}