
/// <summary>
/// Holds x,y,roomId is used by spawner, generated by translator
/// </summary>
public class RoomSpawnInfo
{
    public RoomSpawnInfo(float X, float Y, ushort roomId)
    {
        this.X = X;
        this.Y = Y;
        RoomId = roomId;
    }

    public float X { get; set; }
    public float Y { get; set; }
    public ushort RoomId { get; set; }

}